[theme]
base="light"
primaryColor="#50394c"
backgroundColor="#f4e1d2"
secondaryBackgroundColor="#ffffff"
textColor="#50394c"
font="sans serif"

[server]
enableStaticServing = true

[theme.sidebar]
backgroundColor="#50394c"
secondaryBackgroundColor="#f4e1d2"
textColor="#f4e1d2"
primaryColor="#ffef96"
